/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_professional_activity_DetectionActivity_LeDeviceListAdapter */

#ifndef _Included_com_yj_professional_activity_DetectionActivity_LeDeviceListAdapter
#define _Included_com_yj_professional_activity_DetectionActivity_LeDeviceListAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
