/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_professional_utils_JniCall */

#ifndef _Included_com_yj_professional_utils_JniCall
#define _Included_com_yj_professional_utils_JniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yj_professional_utils_JniCall
 * Method:    process_Data
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_yj_professional_utils_JniCall_process_1Data
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
